spring:
  application:
    name: mindmap-api
  datasource:
    url: jdbc:postgresql://localhost:5433/mindmap
    username: mindmap
    password: mindmap

notion:
  token: ${NOTION_TOKEN}
  version: 2022-06-28